version: 2
jobs:
  build:
    working_directory: ~/deploy
    docker:
      - image: node:4.8.0
    steps:
      - checkout
      - deploy:
          name: Deploy Master to Heroku
          command: |
            ./deploy.sh
workflows:
  version: 2
  production:
    jobs:
      - build:
          filters:
            branches:
              only: production
