version: 2
jobs:
  build:
    working_directory: ~/deploy
    docker:
      - image: buildpack-deps:latest
    parallelism: 1
    steps:
      - checkout
      - deploy:
          name: Deploy beta to Dokku
          command: |
            ./deploy.sh
workflows:
  version: 2
  beta:
    jobs:
      - build:
          filters:
            branches:
              only: "2017"